server:
  port: 8080
  servlet:
    context-path: /identity


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer-key: "HmrU3++N6KHqfjjp8bbuDjSNI1d6suhp+t/OTb+1L8dVES/kHkc7XF9VHj0UtMlo"